# Generated by Django 5.0.2 on 2024-06-13 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CarInterior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CruiseControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExteriorColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FuelEfficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gearbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InteriorColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InteriorMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transmitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condition', models.CharField(choices=[('new', 'Yeni'), ('used', 'İstifadə olunmuş')], max_length=10)),
                ('price', models.IntegerField()),
                ('currency', models.CharField(choices=[('AZN', 'AZN'), ('USD', 'USD'), ('EUR', 'EUR')], max_length=3)),
                ('mileage', models.IntegerField()),
                ('engine_power', models.CharField(max_length=100)),
                ('production_year', models.IntegerField()),
                ('seller', models.CharField(choices=[('new', 'Yeni'), ('used', 'İstifadə olunmuş')], max_length=10)),
                ('additional_notes', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('phone_operator', models.CharField(choices=[('050', '050'), ('051', '051'), ('055', '055'), ('070', '070'), ('077', '077')], max_length=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('vin_code', models.CharField(max_length=100)),
                ('listing_type', models.CharField(choices=[('salon', 'Salon'), ('one_cekilmis', 'One Çəkilmiş')], max_length=20)),
                ('car_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.carbrand')),
                ('car_interior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.carinterior')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_images/')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='advertisement.advertisement')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.carbrand')),
            ],
        ),
        migrations.AddField(
            model_name='advertisement',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.carmodel'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.country'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='cruise_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.cruisecontrol'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='exterior_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.exteriorcolor'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='fuel_efficiency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.fuelefficiency'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='fuel_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.fueltype'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='gearbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.gearbox'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='interior_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.interiorcolor'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='interior_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.interiormaterial'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='other',
            field=models.ManyToManyField(to='advertisement.other'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='parking_sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.parkingsensor'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='seats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.seats'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='car_supplies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.supply'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='transmitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.transmitter'),
        ),
    ]
