# Generated by Django 5.0.2 on 2024-06-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='seller',
            field=models.CharField(choices=[('Personal Seller', 'Şəxsi Satıcı'), ('Seller', 'Satıcı'), ('Company', 'Şirkət')]),
        ),
    ]
