# Generated by Django 5.0.2 on 2024-06-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_advertisement_trade_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='car_supplies',
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='trade_options',
            field=models.CharField(blank=True, choices=[('barter', 'Barter'), ('credit', 'Kredit'), ('all', 'Hamısı')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='car_supplies',
            field=models.ManyToManyField(to='advertisement.supply'),
        ),
    ]
