# Generated by Django 5.0.2 on 2024-06-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0004_remove_advertisement_car_supplies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=models.FileField(upload_to='car_images/'),
        ),
    ]
