"""
Django settings for moto4 project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l2-iim8jksf9vsp32%giha926=r-^7m+_r-9#zori2-td3u9n0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []




INSTALLED_APPS = [
    #default parts
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    #third_part app
    'rest_framework',
    'django_filters',
    'drf_yasg',
    # 'corsheaders',

    #apps
    'companies',
]

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
    ],
}

# from django.utils.translation import gettext_lazy as _

# LANGUAGE_CODE = 'en'

# LANGUAGES = (
#     ('en', _("English")),
#     ('en-us', _("US English")),
#     ('az', _('Azerbaijani')),
   
# )

JAZZMIN_UI_TWEAKS = {
    "theme": "default",  # Burada "default" saxlayın və ya başqa tema istifadə edin
    "dark_mode_theme": None,  # Tünd rejimi istifadə etmək istəmirsinizsə None olaraq saxlayın
    "navbar": "navbar-white navbar-light",  # Ağ rəngli naviqasiya paneli
    "no_navbar_border": True,  # Naviqasiya panelində sərhəd olmasın
    "sidebar": "sidebar-dark-primary",  # Bənövşəyi rəngli yan panel
    "brand_colour": "navbar-purple",  # Bənövşəyi rəngli marka sahəsi
    "accent": "accent-navy",  # Bənövşəyi rəngli vurğu
    "navbar_small_text": False,  # Naviqasiya panelində kiçik mətn olmasın
    "sidebar_small_text": False,  # Yan paneldə kiçik mətn olmasın
    "footer_small_text": False,  # Alt paneldə kiçik mətn olmasın
    "body_small_text": False,  # Bədənin mətnləri kiçik olmasın
    "brand_small_text": False,  # Marka sahəsində kiçik mətn olmasın
    "sidebar_nav_small_text": False,  # Yan paneldə naviqasiya mətnləri kiçik olmasın
    "sidebar_nav_child_indent": True,  # Yan paneldə uşaq elementləri indentasiya olunsun
    "sidebar_nav_compact_style": False,  # Yan paneldə kompakta stil istifadə edilməsin
    "sidebar_nav_flat_style": True,  # Yan paneldə düz stil istifadə edilsin
    "sidebar_disable_expand": False,  # Yan paneldə genişlənmə deaktiv edilməsin
    "sidebar_nav_legacy_style": False,  # Yan paneldə köhnə stil istifadə edilməsin
    "sidebar_nav_child_hide_on_collapse": True,  # Yan paneldə uşaq elementlər kollaps olanda gizlənsin
    "footer_fixed": True,  # Alt panel sabit olsun
    "navbar_fixed": True,  # Naviqasiya paneli sabit olsun
    "sidebar_fixed": True,  # Yan panel sabit olsun
    "button_classes": {  # Düymələrin sinifləri
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
        "default": "btn-default"
    },
    "actions_sticky_top": False,  # Əməliyyatlar yapışqan olmasın
    "show_ui_builder": False,  # UI qurucusu göstərilməsin
}

JAZZMIN_SETTINGS = {
    "site_title": "MOTO 4 Admin",
    "site_header": "MOTO 4 Administration",
    "site_brand": "MOTO 4",
    "site_logo": "path/to/your/logo.png",
    "welcome_sign": "Welcome to MOTO 4 Admin Panel",
    "copyright": "MOTO 4",
    # "search_model": "auth.User",
    # "user_avatar": "",
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'moto4.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'moto4.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'MOTO4',
        'USER': 'moto4admin',
        'PASSWORD': 'WSF4dhR3u3LpYR',
        'HOST': 'localhost',
        'PORT': 5432,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
